- name: Install Apache
  apt:
    name: apache2
    state: present

- name: Allow HTTP through UFW
  ufw:
    rule: allow
    name: 'Apache Full'

- name: Ensure Apache is running
  service:
    name: apache2
    state: started
    enabled: true
